-- Enable Row Level Security (RLS) on Critical Tables
-- Generated by Security Implementation Script

-- Step 1: Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Step 2: Drop existing policies (if any)
DROP POLICY IF EXISTS "Users can view own profile" ON users;
DROP POLICY IF EXISTS "Users can update own profile" ON users;
DROP POLICY IF EXISTS "Users can view own orders" ON orders;
DROP POLICY IF EXISTS "Users can manage own cart" ON cart_items;
DROP POLICY IF EXISTS "Products are publicly viewable" ON products;
DROP POLICY IF EXISTS "Product variants are publicly viewable" ON product_variants;
DROP POLICY IF EXISTS "Categories are publicly viewable" ON categories;

-- Step 3: Create restrictive RLS policies

-- Users table - Users can only access their own data
CREATE POLICY "Users can view own profile" ON users
  FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON users
  FOR UPDATE
  USING (auth.uid() = id);

-- Orders table - Users can only access their own orders
CREATE POLICY "Users can view own orders" ON orders
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own orders" ON orders
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own orders" ON orders
  FOR UPDATE
  USING (user_id = auth.uid());

-- Cart items table - Users can only manage their own cart
CREATE POLICY "Users can view own cart" ON cart_items
  FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own cart" ON cart_items
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own cart" ON cart_items
  FOR UPDATE
  USING (user_id = auth.uid());

CREATE POLICY "Users can delete own cart" ON cart_items
  FOR DELETE
  USING (user_id = auth.uid());

-- Products table - Public read access (for browsing)
CREATE POLICY "Products are publicly viewable" ON products
  FOR SELECT
  USING (is_active = true);

-- Product variants table - Public read access
CREATE POLICY "Product variants are publicly viewable" ON product_variants
  FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM products p 
    WHERE p.id = product_variants.product_id 
    AND p.is_active = true
  ));

-- Categories table - Public read access
CREATE POLICY "Categories are publicly viewable" ON categories
  FOR SELECT
  USING (true);

-- Step 4: Revoke public access from sensitive tables
REVOKE ALL ON TABLE orders FROM PUBLIC;
REVOKE ALL ON TABLE cart_items FROM PUBLIC;
REVOKE ALL ON TABLE users FROM PUBLIC;

-- Step 5: Grant necessary permissions to authenticated users
GRANT SELECT ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO authenticated;

-- Step 6: Create admin role policies (for admin users)
CREATE POLICY "Admins can manage all users" ON users
  FOR ALL
  USING (
    auth.jwt() ->> 'role' = 'admin' OR 
    auth.jwt() ->> 'app_metadata' ->> 'role' = 'admin'
  )
  WITH CHECK (true);

CREATE POLICY "Admins can manage all orders" ON orders
  FOR ALL
  USING (
    auth.jwt() ->> 'role' = 'admin' OR 
    auth.jwt() ->> 'app_metadata' ->> 'role' = 'admin'
  )
  WITH CHECK (true);

CREATE POLICY "Admins can manage all cart" ON cart_items
  FOR ALL
  USING (
    auth.jwt() ->> 'role' = 'admin' OR 
    auth.jwt() ->> 'app_metadata' ->> 'role' = 'admin'
  )
  WITH CHECK (true);

CREATE POLICY "Admins can manage all products" ON products
  FOR ALL
  USING (
    auth.jwt() ->> 'role' = 'admin' OR 
    auth.jwt() ->> 'app_metadata' ->> 'role' = 'admin'
  )
  WITH CHECK (true);

CREATE POLICY "Admins can manage all categories" ON categories
  FOR ALL
  USING (
    auth.jwt() ->> 'role' = 'admin' OR 
    auth.jwt() ->> 'app_metadata' ->> 'role' = 'admin'
  )
  WITH CHECK (true);

-- Step 7: Security verification queries
SELECT 
  '=== RLS IMPLEMENTATION VERIFICATION ===' as section,
  '' as blank1,
  'Verification' as table_type,
  tablename,
  rowsecurity as rls_enabled,
  (SELECT COUNT(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = t.tablename) as policy_count
FROM pg_tables t
WHERE t.schemaname = 'public'
  AND t.tablename IN ('users', 'orders', 'cart_items', 'products', 'product_variants', 'categories')
ORDER BY tablename;