-- Missing Foreign Key Constraints Only
-- Generated by comparing production vs staging databases
-- Execute on Staging Database to fix operations page errors

-- Disable constraints temporarily for faster execution
SET session_replication_role = replica;

-- 1. product_recipes.product_id -> products.id (MISSING)
ALTER TABLE "public"."product_recipes" 
ADD CONSTRAINT "product_recipes_product_id_fkey" 
FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;

-- 2. product_recipes.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."product_recipes" 
ADD CONSTRAINT "product_recipes_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 3. stock_transactions.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."stock_transactions" 
ADD CONSTRAINT "stock_transactions_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 4. production_batches.product_id -> products.id (MISSING - CRITICAL FOR OPERATIONS PAGE)
ALTER TABLE "public"."production_batches" 
ADD CONSTRAINT "production_batches_product_id_fkey" 
FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

-- 5. production_batches.order_id -> orders.id (MISSING - CRITICAL FOR OPERATIONS PAGE)
ALTER TABLE "public"."production_batches" 
ADD CONSTRAINT "production_batches_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 6. batch_ingredients.batch_id -> production_batches.id (MISSING)
ALTER TABLE "public"."batch_ingredients" 
ADD CONSTRAINT "batch_ingredients_batch_id_fkey" 
FOREIGN KEY ("batch_id") REFERENCES "public"."production_batches"("id");

-- 7. batch_ingredients.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."batch_ingredients" 
ADD CONSTRAINT "batch_ingredients_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 8. vendor_orders.vendor_id -> vendors.id (MISSING)
ALTER TABLE "public"."vendor_orders" 
ADD CONSTRAINT "vendor_orders_vendor_id_fkey" 
FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id");

-- 9. vendor_order_items.vendor_order_id -> vendor_orders.id (MISSING)
ALTER TABLE "public"."vendor_order_items" 
ADD CONSTRAINT "vendor_order_items_vendor_order_id_fkey" 
FOREIGN KEY ("vendor_order_id") REFERENCES "public"."vendor_orders"("id");

-- 10. vendor_order_items.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."vendor_order_items" 
ADD CONSTRAINT "vendor_order_items_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 11. customers.profile_id -> profiles.id (MISSING)
ALTER TABLE "public"."customers" 
ADD CONSTRAINT "customers_profile_id_fkey" 
FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id");

-- 12. customer_addresses.customer_id -> customers.id (MISSING)
ALTER TABLE "public"."customer_addresses" 
ADD CONSTRAINT "customer_addresses_customer_id_fkey" 
FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id");

-- 13. orders.delivery_address_id -> customer_addresses.id (MISSING)
ALTER TABLE "public"."orders" 
ADD CONSTRAINT "orders_delivery_address_id_fkey" 
FOREIGN KEY ("delivery_address_id") REFERENCES "public"."customer_addresses"("id");

-- 14. deliveries.order_id -> orders.id (MISSING - CRITICAL FOR OPERATIONS PAGE)
ALTER TABLE "public"."deliveries" 
ADD CONSTRAINT "deliveries_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 15. deliveries.delivery_partner_id -> delivery_partners.id (MISSING - CRITICAL FOR OPERATIONS PAGE)
ALTER TABLE "public"."deliveries" 
ADD CONSTRAINT "deliveries_delivery_partner_id_fkey" 
FOREIGN KEY ("delivery_partner_id") REFERENCES "public"."delivery_partners"("id");

-- 16. subscriptions.customer_id -> customers.id (MISSING)
ALTER TABLE "public"."subscriptions" 
ADD CONSTRAINT "subscriptions_customer_id_fkey" 
FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id");

-- 17. subscriptions.product_variant_id -> product_variants.id (MISSING)
ALTER TABLE "public"."subscriptions" 
ADD CONSTRAINT "subscriptions_product_variant_id_fkey" 
FOREIGN KEY ("product_variant_id") REFERENCES "public"."product_variants"("id");

-- 18. notifications.user_id -> profiles.id (MISSING)
ALTER TABLE "public"."notifications" 
ADD CONSTRAINT "notifications_user_id_fkey" 
FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");

-- 19. communication_log.order_id -> orders.id (MISSING)
ALTER TABLE "public"."communication_log" 
ADD CONSTRAINT "communication_log_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 20. communication_log.customer_id -> customers.id (MISSING)
ALTER TABLE "public"."communication_log" 
ADD CONSTRAINT "communication_log_customer_id_fkey" 
FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id");

-- 21. ingredient_updates.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."ingredient_updates" 
ADD CONSTRAINT "ingredient_updates_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 22. ingredient_updates.previous_supplier -> vendors.id (MISSING)
ALTER TABLE "public"."ingredient_updates" 
ADD CONSTRAINT "ingredient_updates_previous_supplier_fkey" 
FOREIGN KEY ("previous_supplier") REFERENCES "public"."vendors"("id");

-- 23. ingredient_updates.new_supplier -> vendors.id (MISSING)
ALTER TABLE "public"."ingredient_updates" 
ADD CONSTRAINT "ingredient_updates_new_supplier_fkey" 
FOREIGN KEY ("new_supplier") REFERENCES "public"."vendors"("id");

-- 24. ingredients.supplier -> vendors.id (MISSING)
ALTER TABLE "public"."ingredients" 
ADD CONSTRAINT "ingredients_supplier_fkey" 
FOREIGN KEY ("supplier") REFERENCES "public"."vendors"("id");

-- 25. purchase_order_items.purchase_order_id -> purchase_orders.id (MISSING)
ALTER TABLE "public"."purchase_order_items" 
ADD CONSTRAINT "purchase_order_items_purchase_order_id_fkey" 
FOREIGN KEY ("purchase_order_id") REFERENCES "public"."purchase_orders"("id");

-- 26. low_stock_alerts.purchase_order_id -> purchase_orders.id (MISSING)
ALTER TABLE "public"."low_stock_alerts" 
ADD CONSTRAINT "low_stock_alerts_purchase_order_id_fkey" 
FOREIGN KEY ("purchase_order_id") REFERENCES "public"."purchase_orders"("id");

-- 27. production_batch_items.batch_id -> production_batches.id (MISSING)
ALTER TABLE "public"."production_batch_items" 
ADD CONSTRAINT "production_batch_items_batch_id_fkey" 
FOREIGN KEY ("batch_id") REFERENCES "public"."production_batches"("id");

-- 28. production_batch_items.order_id -> orders.id (MISSING)
ALTER TABLE "public"."production_batch_items" 
ADD CONSTRAINT "production_batch_items_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 29. production_batch_items.order_item_id -> order_items.id (MISSING)
ALTER TABLE "public"."production_batch_items" 
ADD CONSTRAINT "production_batch_items_order_item_id_fkey" 
FOREIGN KEY ("order_item_id") REFERENCES "public"."order_items"("id");

-- 30. production_batch_items.product_id -> products.id (MISSING)
ALTER TABLE "public"."production_batch_items" 
ADD CONSTRAINT "production_batch_items_product_id_fkey" 
FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

-- 31. batch_orders.batch_id -> production_batches.id (MISSING)
ALTER TABLE "public"."batch_orders" 
ADD CONSTRAINT "batch_orders_batch_id_fkey" 
FOREIGN KEY ("batch_id") REFERENCES "public"."production_batches"("id");

-- 32. batch_orders.order_id -> orders.id (MISSING)
ALTER TABLE "public"."batch_orders" 
ADD CONSTRAINT "batch_orders_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 33. batch_order_items.batch_id -> production_batches.id (MISSING)
ALTER TABLE "public"."batch_order_items" 
ADD CONSTRAINT "batch_order_items_batch_id_fkey" 
FOREIGN KEY ("batch_id") REFERENCES "public"."production_batches"("id");

-- 34. batch_order_items.order_id -> orders.id (MISSING)
ALTER TABLE "public"."batch_order_items" 
ADD CONSTRAINT "batch_order_items_order_id_fkey" 
FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");

-- 35. batch_order_items.order_item_id -> order_items.id (MISSING)
ALTER TABLE "public"."batch_order_items" 
ADD CONSTRAINT "batch_order_items_order_item_id_fkey" 
FOREIGN KEY ("order_item_id") REFERENCES "public"."order_items"("id");

-- 36. ingredient_unit_conversions.ingredient_id -> ingredients.id (MISSING)
ALTER TABLE "public"."ingredient_unit_conversions" 
ADD CONSTRAINT "ingredient_unit_conversions_ingredient_id_fkey" 
FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id");

-- 37. packaging_materials.supplier -> vendors.id (MISSING)
ALTER TABLE "public"."packaging_materials" 
ADD CONSTRAINT "packaging_materials_supplier_fkey" 
FOREIGN KEY ("supplier") REFERENCES "public"."vendors"("id");

-- Re-enable constraints
SET session_replication_role = DEFAULT;

-- Verify only the new constraints were added
SELECT 
    tc.table_name, 
    kcu.column_name, 
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name,
    tc.constraint_name
FROM information_schema.table_constraints AS tc 
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
    AND tc.table_schema = 'public'
    AND tc.constraint_name IN (
        'product_recipes_product_id_fkey',
        'product_recipes_ingredient_id_fkey',
        'stock_transactions_ingredient_id_fkey',
        'production_batches_product_id_fkey',
        'production_batches_order_id_fkey',
        'deliveries_order_id_fkey',
        'deliveries_delivery_partner_id_fkey'
    )
ORDER BY tc.table_name, kcu.column_name;
